### ISSUE TITLE
all console output is gone once tests are complete

### ISSUE THREAD

**Issue by abbood** [Ahmed-Ali/Cucumberish#10]
`given` user launched test
`when` all tests passed (or failed)
`then`
**expected** the output of the tests should remain on the console
**actual** the output of the tests are all gone

**Comment by Ahmed-Ali** [comment]
I did not encounter such issue before!
Which Xcode version do you use?

**Comment by abbood** [comment]
Version 7.2.1 (7C1002)

**Comment by Ahmed-Ali** [comment]
I am currently using 7.3, and previously 7.2 and never had such an issue!
However, this issue is not related to Cucumberish; if this issue exist, it will be there with any other app launches. It has something to do with Xcode apart from Cucumberish!
