### ISSUE TITLE
How to execute tests in parallel?

### ISSUE THREAD

**Issue by olyv** [Ahmed-Ali/Cucumberish#122]
Hi, 
There is an option to run test in parallel in Xcode 10 ("Execute in parallel on simulator" ). That option works fine with XCTest only but I am not sure how to do it with Cucumberish. In other words, how to split `Cucumberish.executeFeatures` between several classes inheriting `XCTestCase`. I asked the same question on [Stackoverflow](https://stackoverflow.com/q/56855114/2504101)  but it doesn't seem to receive a lot of attention :) Has anyone managed to parallelize Cucumberish tests?

**Comment by olyv** [comment]
yeah, I could solve my problem by subclassing CucumberishInitializer but Xcode test parallelization works in unpredictable way and I could have up to 2 -3 simulators at a time. After all, I had to create my own sharder and refused using Cucmberish in favour of different Cucumber-like swift library

**Comment by wiralegawa** [comment]
can u share your problem solving @olyv ? i still looking at doing parallelization in cucumberish 🙇 . thank you

**Comment by Mackster7** [comment]
I've successfully implemented parallel UI testing by leveraging multiple feature files and enabling the parallel execution option at the UI target level. Here's how to set it up:

**Prerequisites**

First, you'll need to delete all existing simulators. This is a one-time setup requirement:
`xcrun simctl delete all`


**How It Works**

- Xcode identifies each feature file as a separate test class
- Each test class runs on its own simulator instance
- Multiple simulators run concurrently, significantly reducing total test execution time

**Implementation Steps**

- Create multiple feature files to distribute your test scenarios
- In your UI target settings, enable the "Execute in Parallel" option
- Ensure you have created multiple feature files for maximum parallelization benefit

This approach allows for efficient concurrent testing with minimal configuration changes to your existing test suite.
