### ISSUE TITLE
Reporting: Can't click into the source file from Xcode report navigator when there is a space in app name

### ISSUE THREAD

**Issue by vincentkjj** [Ahmed-Ali/Cucumberish#13]
I've discovered with v0.0.7 that we are not able to click into the report navigator after a case fails.
We have the setting SRC_ROOT=@\"$(SRCROOT)\"

On debugging we've noticed that parseFeatureFiles method of CCIFeaturesManager.m is not handling such case correctly (the original string has URL encoded spaces into %20, but not handled in code)

```objective-c
NSString * localPath = [[filePath.absoluteString stringByReplacingOccurrencesOfString:[[NSBundle bundleForClass:[self class]] bundlePath] withString:@""] stringByReplacingOccurrencesOfString:@"file://" withString:@""];
```

This following logic works for us

```objective-c
NSString * testBundlePath = [[NSBundle bundleForClass:[self class]] bundlePath];
NSString * localPath = [[[filePath.absoluteString stringByRemovingPercentEncoding]
                                     stringByReplacingOccurrencesOfString:testBundlePath withString:@""]
                                    stringByReplacingOccurrencesOfString:@"file://" withString:@""];
```

If this looks good to you, I'll open a PR.

**Comment by Ahmed-Ali** [comment]
Hi @vincentkjj 
Thanks for your contribution.
The issue can be reproduced here.
Your fix works as well. Please open a PR.

Thanks

**Comment by vincentkjj** [comment]
Thanks! PR https://github.com/Ahmed-Ali/Cucumberish/pull/14

**Comment by Ahmed-Ali** [comment]
Hi @vincentkjj 
sorry for my late reply. PR has been merged into develop branch and I will prepare a minor release for the master to include this fix.
