### ISSUE TITLE
The project is clearly abandoned, at least state it as such in the readme

### ISSUE THREAD

**Issue by broken-bytes** [Ahmed-Ali/Cucumberish#137]
The commit history already shows, there has not been put any work into the project in years.
The last release is almost four years old. 

The framework is even listed on the official Cucumber Website, thus many people land here, not knowing this project is dead.

Please state that the project is abandoned and, if applicable, link to a more maintained fork of this project.

**Comment by jfahrenkrug** [comment]
It looks like this one is actively maintained: https://github.com/Tyler-Keith-Thompson/CucumberSwift

**Comment by Ahmed-Ali** [comment]
Thank you for bringing it up. And apologies I haven't done much work on this repo for a while. I will update the readme file to mention that I am unable to commit to actively maintaining it and note the need for maintainers.
