### ISSUE TITLE
Not support XCode 12?

### ISSUE THREAD

**Issue by Mikuu** [Ahmed-Ali/Cucumberish#138]
All our tests are running good with XCode 11.5, but when running with XCode12, will get error: 

```commandline
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No target application path specified via test configuration: (null)'
```

to:

```swift
let application = XCUIApplication()
```

Does anyone make Cucumberish working with XCode 12

**Comment by nishithcitc** [comment]
I believe that it should work. I am working on Xcode 12.4. I can't see any issue.
And Cucumbarish has nothing to do with 
`let application = XCUIApplication()`

**Comment by broken-bytes** [comment]
It’s the load order. You need to define your Testapplication lazily after the init of cucumberish

**Comment by Mikuu** [comment]
good, already made it works, thanks.
