### ISSUE TITLE
Xcode 12.5 problem

### ISSUE THREAD

**Issue by sidekickr** [Ahmed-Ali/Cucumberish#141]
I believe that cucumberish breaks on Xcode 12.5. In the below method in cucumberish.m the allocation of the invocation test fails to compile. Specifically this line:

`            invocationTest =  [[self alloc] initWithInvocation:inv];`

My local fix is to do this:
`            invocationTest =  [((id)[self alloc]) initWithInvocation:inv];`

And to add an `@import Foundation;` to the top of cucumberish.m.

I'll work on a pull request later when I have some free time. If someone wants to get to it first, be my guest.

`+ (nullable XCTestCase *)cucumberish_testCaseWithSelector:(SEL)selector
{
    CCIFeature * feature = [[CCIFeaturesManager instance] getFeatureForClass:[self class]];
    XCTestCase * invocationTest;

    for(CCIScenarioDefinition * s in feature.scenarioDefinitions){
        NSString * scenarioName = NSStringFromSelector(selector);
        if ([s.name isEqualToString:scenarioName]){
            [Cucumberish instance].scenarioCount++;
            NSInvocation * inv = [Cucumberish invocationForScenario:s feature:feature featureClass:[self class]];
            invocationTest =  [[self alloc] initWithInvocation:inv];
            break;
        }else if([s.keyword isEqualToString:(NSString *)kScenarioOutlineKeyword]){
          NSRange range = [scenarioName rangeOfCharacterFromSet:[NSCharacterSet decimalDigitCharacterSet] options:NSBackwardsSearch];
            NSInteger exampleIndex = [[scenarioName substringWithRange:range] integerValue] - 1;
            NSString * scenarioOutlineName = [Cucumberish exampleScenarioNameForScenarioName:s.name exampleAtIndex:exampleIndex example:s.examples.firstObject];
            if([scenarioName isEqualToString:scenarioOutlineName]){
                CCIExample * example = s.examples.firstObject;
                NSInvocation * inv = [Cucumberish invocationForScenarioOutline:s example:example exampleIndex:exampleIndex feature:feature featureClass:[self class]];
                invocationTest =  [[self alloc] initWithInvocation:inv];
                break;
            }
        }
    }
    return invocationTest;
}`

**Comment by duyquang91** [comment]
@sidekickr I already created a PR for this: https://github.com/Ahmed-Ali/Cucumberish/pull/140. It is still in review so you can use my fork repository for workaround in the meanwhile.

**Comment by sidekickr** [comment]
Awesome, thank you.

**Comment by broken-bytes** [comment]
It’ll will stay in review, project has been dead for months

**Comment by iammike** [comment]
Much longer than that, more or less.

**Comment by broken-bytes** [comment]
There was a commit on dev for SPM half a year ago. Besides that, it has been years.

**Comment by codechallengeios** [comment]
A version with this fix will be released?

**Comment by henawey-t** [comment]
Release 1.4.0 fix this. I'll close the ticket.
