### ISSUE TITLE
Error thrown: No visible @interface for 'Cucumberish' declares the selector 'initWithInvocation:'

### ISSUE THREAD

**Issue by nagashreea** [Ahmed-Ali/Cucumberish#143]
<img width="883" alt="Screenshot 2021-09-06 at 3 54 09 PM" src="https://user-images.githubusercontent.com/88699633/132203017-19177b60-ad4e-44e0-9f3b-57d2809e170e.png">
Hi @Ahmed-Ali . I Am getting the below error while building the app. @brentleyjones @patmalt @TitouanVanBelle @vincentkjj @dgommers 
Error: Bad receiver type 'void (*)()' in Cucuber loader
Error: No visible @interface for 'Cucumberish' declares the selector 'initWithInvocation:'
<img width="903" alt="Screenshot 2021-09-02 at 4 23 16 PM" src="https://user-images.githubusercontent.com/88699633/131832301-bfa2e32a-9f1e-486e-aab6-7d3a6514f7b9.png">

**Comment by nagashreea** [comment]
@brentleyjones @patmalt @TitouanVanBelle @vincentkjj @Ahmed-Ali : Please help.

**Comment by henawey-t** [comment]
If I'm not mistaken, it solved with v1.4.0 version.

**Comment by Mahmoud-Bassuni** [comment]
thank you so much @henawey-t  its working fine now
