### ISSUE TITLE
BDD tests pass even though their definitions are missing.

### ISSUE THREAD

**Issue by ilife** [Ahmed-Ali/Cucumberish#17]
Steps:

1. Create a test scenario with a Given step as "I have a very cool app" in feature file.
2. Implement its definition in the native code.
3. Create an another test scenario with a Given step as "I have a very cool app and website" in feature file.
4. Don't implement its definition in native code. 
5. Run BDD tests. 
6. All tests pass even though another test scenario was never implemented in native code.

This happens only when the implemented step string acts as the substring of the step in feature file.

**Comment by Ahmed-Ali** [comment]
Issue has been fixed and will be included in master with the next update.
Thanks @ilife for reporting it.
