### ISSUE TITLE
Steps with accent character crash

### ISSUE THREAD

**Issue by asengmany** [Ahmed-Ali/Cucumberish#21]
Hi,

Writing steps with accented character like 'é' or  'ô' make the test crash. I got this error

failed: caught "NSRangeException", "*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: Range or index out of bounds"

I dont have time currently to dig into it but if you could that would be awesome.

Aside from that it works perfectly :)

**Comment by Ahmed-Ali** [comment]
Hi @asengmany 
I have tried to just add some of these accented characters to few of the steps I have, and it worked fine.
So if it is possible to provide more information or steps to reproduce, it would be great!
Thanks

**Comment by asengmany** [comment]
```
 MatchAll("^I should see text containing \"([^\\\"]*)\"$") { (args, userInfo) -> Void in
            let value = args![0]
            let predicate : NSPredicate = NSPredicate(format:"label CONTAINS \"\(value)\"")
            let e = self.application.staticTexts.containing(predicate)
            CCISAssert(e.element.exists == true, "Could not find text containing \(value)")
        }
```

And my step

`    Then I should see text containing "é"`

It doesnt even execute the function

**Comment by asengmany** [comment]
In 
`- (CCIStepDefinition *)findDefinitionForStep:(CCIStep *)step amongDefinitions:(NSArray *)definitions inTestCase:(id)testCase`

You are using 
`        NSRange searchRange = NSMakeRange(0, [step.text lengthOfBytesUsingEncoding:NSUTF8StringEncoding]);
`

 But unicode character can be more than 1 byte I think so that's why it failed with error 'Range or index out of bounds' 

Replacing this line by 
        `NSRange searchRange = NSMakeRange(0, step.text.length);`  works for me

How is that working in your case though?

Thanks
