### ISSUE TITLE
Bridging headers not imported when Podfile has 'use_frameworks!' 

### ISSUE THREAD

**Issue by Shashikant86** [Ahmed-Ali/Cucumberish#25]
Cocoapod installation seems to have an issue when `Podfile` has 

`use_frameworks!`

Not sure, it's issue with Cocoapods or Cucumberish but it's not working 

Error says 
``
/Users/Shashi/Desktop/CucumberishPodTests/CucumberishPodTestsCucumberTests/CucumberishPodTestsCucumberTests-Bridging-Header.h:14:9: error: 'Cucumberish.h' file not found
#import "Cucumberish.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/Shashi/Desktop/CucumberishPodTests/CucumberishPodTestsCucumberTests/CucumberishPodTestsCucumberTests-Bridging-Header.h'
``

**Steps to Reproduce**

Add `use_frameworks!` to `Podfile` and try running tests

**Comment by Ahmed-Ali** [comment]
I am able to reproduce the issue. When using use_framework! you just need to
`
import Cucumberish`
in the swift file. But there is another issue I found when doing that (Cucumberish unable to report errors properly), and I am working on a fix for that.
Thanks for reporting it! I will update the documentation accordingly.

**Comment by Ahmed-Ali** [comment]
The issue has been resolved and the readme instructions updated accordingly.
Please delete your Podfile.lock and rerun pod install to get version 1.0.3
And as mentioned, use the following in your swift files instead of bridging header.
```
import Cucumberish
``
