### ISSUE TITLE
Release 1.0.4 with regex fixes

### ISSUE THREAD

**Issue by brentleyjones** [Ahmed-Ali/Cucumberish#27]
Hi,

Can we get develop merged into master and cut a new CocoaPods release? I'm currently pinned to the top of the develop branch in my local environment, but would like to use a tagged release to make CocoaPods run faster.

Thanks!

**Comment by Ahmed-Ali** [comment]
Sure!
Will work on it now.

**Comment by Ahmed-Ali** [comment]
Done!
