### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ollitapa** [Ahmed-Ali/Cucumberish#28]
Any chance of getting support for Carthage dependency manager?

**Comment by Ahmed-Ali** [comment]
This was planned long time ago and I got it in place (in local dev branch as I can recall), and it that time I got some troubles with it. I think most of these issues has been already resolved by now. I will give it another try as soon as possible.

**Comment by ollitapa** [comment]
That would be great! Thanks!

**Comment by brentleyjones** [comment]
Cucumberish is our last CocoaPods dependency for our UI tests. Supporting Carthage would be awesome!

**Comment by Ahmed-Ali** [comment]
I know I am too late to respond to that, but I will do my best to get it sorted out asap.
Apologises guys!

**Comment by dgommers** [comment]
Unfortunately, I don't have any experience with Carthage (yet). Otherwise I would have fixed it. @ollitapa are you be able to tell us what needs to be added/changed?

**Comment by Ahmed-Ali** [comment]
I have added the support for Carthage (still on develop at this moment) and working now on the documentation to clarify the installation steps.

Thanks guys for your support!

**Comment by Ahmed-Ali** [comment]
It is now on master. Please check it out and let me know if you have any feedback.
Make sure not to miss this step:
```ObjectiveC
            [Cucumberish instance].testTargetSrcRoot = SRC_ROOT;
```

**Comment by brentleyjones** [comment]
I'll be checking this out soon. Thanks! 🎉

**Comment by ollitapa** [comment]
Seems to work for me! Thanks! 🎈
