### ISSUE TITLE
Escape characters 

### ISSUE THREAD

**Issue by cepages** [Ahmed-Ali/Cucumberish#29]
This is one of my scenarios:

```
Feature: Login Feature

Scenario: Login Scenario

Given the app is running
And I wait to see "Login" button
And I wait to see "Login" field
And I wait to see "Password" secure field
And I write "carlos+2@company.com" in the "Login" field
And I write "Password" in the "Password" secure field
And I tap the "Login" button 1 time
Then I wait to see "notificationsView" view
```

`can+2@company.com` is written in the field instead `carlos+2@company.com`

![screen shot 2016-11-18 at 18 01 05](https://cloud.githubusercontent.com/assets/5259830/20440698/0a74a942-adb9-11e6-8019-8561448fd086.png)

Any ideas?

**Comment by Ahmed-Ali** [comment]
how do you define the matching step?

**Comment by cepages** [comment]
It fits with the common one in CommonStepDefinitions.swift:

```
        //When/And/But/When I write "Ahmed" in the "Name" field
        MatchAll("^I write \"([A-Za-z0-9._%+-@]+)\" (?:into|in) (?:the )?\"([^\\\"]*)\" (field|text view|secure field)$") { (args, userInfo) -> Void in
            let type = args?[2]
            let label = args?[1]
            let element = self.elementByLabel(label!, type: type!)
            element.tap()
            element.typeText((args?[0])!)
        }
```

**Comment by Ahmed-Ali** [comment]
I tried to reproduce it, but here is what I get in the matching step definition
<img width="1388" alt="screen shot 2016-11-28 at 10 43 54 am" src="https://cloud.githubusercontent.com/assets/5157350/20663395/a7273552-b557-11e6-8471-e1d1ccf977a3.png">

It seems to be working fine with me

**Comment by Ahmed-Ali** [comment]
mm, I think I might be able to guess why. Does the text field has auto-correct enabled? if so, that might be the reason. It has nothing to do with the step or its definition, it is just the auto correction :)
