### ISSUE TITLE
Including release notes in Github

### ISSUE THREAD

**Issue by dgommers** [Ahmed-Ali/Cucumberish#30]
Usually I directly open up the [Releases tab](https://github.com/Ahmed-Ali/Cucumberish/releases) to see what is new in the latest version. However, when I manually opened up the diff between v1.0.4 and v1.0.5, I found out that there is an actual [CHANGELOG.md](https://github.com/Ahmed-Ali/Cucumberish/blob/master/CHANGELOG.md). 

Can we start using Github's native tab to be consistent with other projects? [Quick](https://github.com/Quick/Quick/releases) is a prefect example. I would be happy to help.

**Comment by Ahmed-Ali** [comment]
I believe that will make it much easier and more accessible!
Will update the latest two releases and will make sure the same is applied to future releases.

Thanks Derk!

**Comment by dgommers** [comment]
Looks good, thanks.
