### ISSUE TITLE
Where do I add the objc.m file?

### ISSUE THREAD

**Issue by bartpowers** [Ahmed-Ali/Cucumberish#32]
I am interested in trying out your cucumber solution.  I installed the framework via carthage into a swift test target.

but I am getting the following error:
CucumberishInitilizer.m:16:6: error: use of undeclared identifier 'CucumberishInitializer'; did you mean 'CucumberishInit'?
CucumberishInitilizer.m:16:6: error: bad receiver type 'void (*)()'

I am having trouble getting this up and running after following the installation tutorial

**Comment by dgommers** [comment]
Maybe this helps: 

1. Ensure you have the `CucumberishInitializer` swift file.
2. This file needs to be in the same target as the Objective-C m file.
3. If thats all right, it might be that your class/method is not exposed as Objective-C interface. Prefix the Swift class with @objc to make it available.

If not, please share your target setup and file contents.

**Comment by Ahmed-Ali** [comment]
Beside the suggestions Derk suggested, have you imported the the swift header file?
By default the swift header file will be *TestTargetName*-Swift.h

**Comment by bartpowers** [comment]
THanks for the quick responses!  I found my problem.... the default swift header file wasn't the same as the targets name.  I thought it was MX-Tests-Swift.h... turns out it was MX_Tests-Swift.h
