### ISSUE TITLE
Support changing `prettyNamesAllowed` for feature and/or scenario

### ISSUE THREAD

**Issue by brentleyjones** [Ahmed-Ali/Cucumberish#34]
I'm currently using `prettyNamesAllowed` and really like it. I've recently started using xcpretty and ran into an issue: https://github.com/supermarin/xcpretty/issues/256

I'm wondering if we can split this bool into two, to allow for me to continue to have pretty names for the the suite names but have matchable names (non-pretty) for the test cases.

**Comment by Ahmed-Ali** [comment]
I believe this should be easily doable, and I also agree it should be implemented. Going to give it a try.

**Comment by Ahmed-Ali** [comment]
The fix pushed to develop branch and will be included in the release.
Thanks man for your support!
