### ISSUE TITLE
Support subdirectories

### ISSUE THREAD

**Issue by brentleyjones** [Ahmed-Ali/Cucumberish#36]
Currently if the feature directory has subdirectories the features are not picked up. When you have lots of feature files is makes sense to be able to organize them on the filesystem in subdirectories,

**Comment by brentleyjones** [comment]
When I get the chance I'll try to take a stab at creating a PR for this one.

**Comment by vincentkjj** [comment]
@brentleyjones any news with this one? We are in need of this function too and I am thinking to give it a try if you haven't yet.

**Comment by brentleyjones** [comment]
I haven't yet. Been on leave with a newborn. It will be a couple weeks at least before I could get back to this.

**Comment by Ahmed-Ali** [comment]
Congratulations @brentleyjones for the newborn :)
Subdirectory support is now available on develop and will be on master soon.
Thanks!
