### ISSUE TITLE
JSON output documentation

### ISSUE THREAD

**Issue by Ahmed-Ali** [Ahmed-Ali/Cucumberish#42]
We need to document the usage of the CIJSONDumper

**Comment by lutzj82** [comment]
I noticed that the output file is not created when I run my tests.  the condition that checks if scenariosRun == scenarioCount is never satisified b/c scenarioCount is only incremented after the function call to invokeScenario, which means its one behind.  I made a change locally that just incremented the counter prior to invoking the scenario, so if you want I can write up a few tests and create a PR...

As another note...It'd be nice to specify the results location and/or result file name.

Thanks

**Comment by Ahmed-Ali** [comment]
Thanks a lot @lutzj82 for your input. It will be nice if you can help with that.
And I will do my best to get the documentation issue resolved asap. It should help avoiding unneeded confusion.

**Comment by brentleyjones** [comment]
I would be weary of moving the `scenariosRun` increment. It's the way it is to support the `beforeHook` and `afterHook` calling.

**Comment by lutzj82** [comment]
@brentleyjones, The only change would be in the position where scenarioCount, not scenariosRun would be incremented

**Comment by brentleyjones** [comment]
:+1:

**Comment by brentleyjones** [comment]
This has been released in v1.2.0. Cocoa pods will be updated as soon as @Ahmed-Ali pushes it to trunk.
