### ISSUE TITLE
Don't run a specific scenario if marked with "manual' tag

### ISSUE THREAD

**Issue by dmortim3** [Ahmed-Ali/Cucumberish#48]
Looking at if Cucumberish can exclude a scenario from a test if it has a specific tag, for example "Manual". Any thoughts on how this can be achieved? If this is not possible i'll look at adding it. Thanks.

**Comment by brentleyjones** [comment]
You can exclude tags in the `executeFeatures` method.

**Comment by dmortim3** [comment]
I actually looked at this a couple of months ago and at the time this was not possible. After upgrading to the latest version both include and exclude options by tag are no possible. 

Thanks for the awesome port.
