### ISSUE TITLE
CucumberishInitializer and CucumberishSwiftInit not recognised in .m file

### ISSUE THREAD

**Issue by EricDeRegter** [Ahmed-Ali/Cucumberish#49]
I was following the wiki regarding the installation using cocoapods. Everytime I tried to run the tests the .m file was giving me errors on line `[CucumberishInitializer CucumberishSwiftInit];` I think they didn't recognise `CucumberishInitializer` and `CucumberishSwiftInit`. Making them both `public` fixed it. Maybe you could update the wiki?

```
import Foundation
import Cucumberish

public class CucumberishInitializer: NSObject {
  public class func CucumberishSwiftInit()
  { ... }
}
```

**Comment by brentleyjones** [comment]
I added `public` to the Wiki page. Thanks for opening the issue @EricDeRegter!
