### ISSUE TITLE
JSON output, Scenario outlines are not counted in Jenkins Cucumber Report

### ISSUE THREAD

**Issue by Gerard-A** [Ahmed-Ali/Cucumberish#50]
We are using the Jenkins Cucumber Report plugin (https://github.com/jenkinsci/cucumber-reports-plugin) to generate a html report from the Cucumberish JSON output. We use one feature file to  execute scenarios on iOS Using Cucumberish and Android using Cucumber-JVM. The feature file contains Scenarios and Scenario Outlines.
I noticed that the number of tests in the iOS results are lower than in the Android results.  
It seems that the Cucumber Report does not count scenarios in Scenario Outlines.
A difference was noticed in the json output. Cucumber-JVM logs Scenario Outline results as:
        _"keyword": "Scenario Outline",
        "type": "scenario",_
where Cucumberish logs it as:
        _"keyword" : "Scenario Outline",
        "type" : "scenario_outline",_

Could it be that the "type" parameter should be set to "scenario" instead of "scenario_outline" in the Cucumberish JSON output?

**Comment by ereynolds-agamatrix** [comment]
Hi, Gerard,

This is a good catch. I will take a look at this issue. We had originally set the type to "scenario_outline" thinking it would be useful to have outlines be recognized as its own type but we had not considered Jenkins looking for the "scenario" for parsing purposes.  It should be an easy fix.

-Erik

**Comment by brentleyjones** [comment]
This is merged into `develop` @Gerard-A. Let us know if you run into any issues. We should cut a release sometime next week with the changes if everything is good.

**Comment by brentleyjones** [comment]
This has been released in v1.2.0. Cocoa pods will be updated as soon as @Ahmed-Ali pushes it to trunk.
