### ISSUE TITLE
addUIInterruptionMonitor gives an exception Internal error: no current scope to add handler

### ISSUE THREAD

**Issue by dipikasrivastava16** [Ahmed-Ali/Cucumberish#52]
When I am trying to interact with a system dialog which comes up in the application before accessing contacts, i try to addUIInterruptionMonitor before the system alert is expected and write a handler for interacting with the same.
On run time i get the exception:  caught "NSInternalInconsistencyException", "Internal error: no current scope to add handler Permission Dialog to."

Has anyone else faced a similar problem?

**Comment by brentleyjones** [comment]
Yes. It's because each scenario is a new `XCTestCase`. No real solution yet that I know of.

**Comment by georgiosantoniadis** [comment]
A possible solution might be found here:
https://github.com/Ahmed-Ali/Cucumberish/issues/47
