### ISSUE TITLE
Multiple Examples tables for a scenario outline

### ISSUE THREAD

**Issue by Wayne-Morgan** [Ahmed-Ali/Cucumberish#54]
I supply different Examples to the same scenario based on tags.  The tags may be for different test durations (a brief daily test vs a more comprehensive weekly test), or for platforms with different capabilities (desktop platform may support different file formats to android platform).  I already use this functionality on other platforms, and would like to use the same feature files on iOS to reduce duplication.
e.g.

  Scenario Outline: Scenario with multiple examples tables
    Given the test equipment is set up
    When <test_data> is applied
    Then the result will be <test_result>

    @daily_test
    Examples:
      | test_data             | test_result             |
      | short_daily_test_data | short_daily_test_result |

    @weekly_test
    Examples:
      | test_data               | test_result               |
      | longer_weekly_test_data | longer_weekly_test_result |

I've noticed two problems with this:
1) Although the scenario is run twice (once for each item in each table), the data is always taken from the first table.  If subsequent tables have more items than the first, then there will be a crash due to an attempt to reference beyond the bounds of the first table.
I've tried fixing this locally by passing the example table CCIExample* to invocationForScenarioOutline, but problem 2 remains.

2) It seems that tags for the example tables are ignored.  After the fix for problem1, then the above test will execute both daily and weekly tests regardless of the tags supplied.

**Comment by Wayne-Morgan** [comment]
I think I have a solution for this.  Just reviewing internally before submitting a PR.

**Comment by brentleyjones** [comment]
This is merged into develop @Wayne-Morgan. Let us know if you run into any issues. We should cut a release sometime soon with the changes if everything is good.

**Comment by brentleyjones** [comment]
This has been released in v1.2.0. Cocoa pods will be updated as soon as @Ahmed-Ali pushes it to trunk.
