### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by sbt007** [Ahmed-Ali/Cucumberish#62]
Currently the podfile does not allow installation if it is a tvOS project. 
Adding something like s.tvos.deployment_target = "10.0" to the podspec should solve this.

I personally do not think that any other special changes to Cucumberish is needed, but have not looked deeper. I was able to run the sample tests provided on a Apple TV simulator. XCode/XCTest supports both iOS and tvOS.

**Comment by brentleyjones** [comment]
I'll look into this next week, see if we can update both the Carthage and CocoaPods to support tvOS.

**Comment by brentleyjones** [comment]
@sbt007 I added support for tvOS to both Carthage and CocoaPods, in the develop branch. Let me know if everything works for you. If so, it should go out in a release sometime soon.

**Comment by sbt007** [comment]
Thanks @brentleyjones - I will try it out.

**Comment by brentleyjones** [comment]
This has been released in v1.2.0. Cocoa pods will be updated as soon as @Ahmed-Ali pushes it to trunk.
