### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by IGZJoseAngelCuadrado** [Ahmed-Ali/Cucumberish#66]
Hi!

I'm creating a project with several features files and its corresponding steps in Swift. The integration is OK and I have achieved that all tests passed. However, when I try to get the results report, I discover that this report is not generated.

In more detail, I have 3 feature files, and 3 swift files with steps definition, and I call these definitions from my cucumberish initializer. Debugging the library, I have discovered that, in the last test, after run the steps of this test, testing process is over, without run after methods neither write the output file (Cucumberish.m -> executeScenario() ). I run my tests with cmd+U. Also, I detect that when I run only one of the features (no matter which) from test navigator, Cucumberish creates the file, but the rest of the features not tested are skipped or failed.

I hope you can solve this soon! Thank you for the library!

**Comment by alexruperez** [comment]
+1

**Comment by IGZJoseAngelCuadrado** [comment]
Ok, I fix the issue. Finally, the problem was with one of my test, that the code couldn't find the button. However, there will be a review when Xcode finish suddenly the tests. Maybe, with the flag "fixMissingLastScenario" activated and checking if this flag is activated and scenarios run is equal to count of scenarios - 1, in this case, write the report.
