### ISSUE TITLE
Step matching definition that only contains a part of the step's name

### ISSUE THREAD

**Issue by TitouanVanBelle** [Ahmed-Ali/Cucumberish#69]
I have the following scenario

```
Scenario: As a publisher, I want to start the SDK with AppID and UserID
     When I start the SDK with an AppID and a UserID
     Then the SDK should start
```

When the first step is executed it matches the following definition which only partially contains the step's name:

```
Match(["When", "And"], "I start the SDK with an AppID") { (args, userInfo) in
    //
}
```

Is that normal or is it a bug? This only way around it at the moment is to write the step definition with ^ and $

```
Match(["When", "And"], "^I start the SDK with an AppID$") { (args, userInfo) in
    //
}
```

**Comment by brentleyjones** [comment]
Since it uses regular expressions, you need to use `^` and `$`. I wouldn't count it as a bug, right now.
