### ISSUE TITLE
i must restart xcode everytime in order for the tests to run properly

### ISSUE THREAD

**Issue by abbood** [Ahmed-Ali/Cucumberish#8]
`given` i have written several features to be tested
`and` I run UI tests
`and` the tests run successfully
`when` I try to run the UI tests again
`then`
**expected** the tests should run successfully
**actual** all the tests are skipped.. and i get a "tests succeeded" all the time
**workaround** restart xcode everytime, in order to successfully run tests

note: the test that actually runs and is marked successfully shows as "null" in the Xcode test navigator

![screen shot 2016-04-27 at 9 22 36 am](https://cloud.githubusercontent.com/assets/774379/14843518/9936d828-0c59-11e6-91ad-4a24bcef73c1.png)

**Comment by abbood** [comment]
work around:

type this into ~/.bash_profile
```
function killX {
  kill `ps -ax | grep MacOS/Xcode | awk '{print $1}' | head -n1`
}

function startX {
  open '/Applications/Xcode.app'
}


function restartX {
  killX
  startX
}

function restartL {
  killX
  open '/path/to/your/project/projectName.xcodeproj'
}```

**Comment by dmortim3** [comment]
I've also seen this problem. 

If the test target is executed using ⌘U then the tests will run without a restart. Of course it would be great to get this working from the test navigator...

**Comment by abbood** [comment]
@dmortim3 so what's the difference? what does <kbd>⌘U</kbd> mean?

**Comment by dmortim3** [comment]
⌘U is the same as using "Product/Test" from the menu. This will execute tests for your selected scheme.

**Comment by Ahmed-Ali** [comment]
@abbood are you trying to execute the case using the small play button beside the test case?

**Comment by abbood** [comment]
yes @Ahmed-Ali 
![screen shot 2016-04-28 at 8 19 56 am 2016-04-28 08-20-14](https://cloud.githubusercontent.com/assets/774379/14876091/1467aca0-0d1a-11e6-9063-11e7794bf7ee.png)

**Comment by Ahmed-Ali** [comment]
I didn't think this should be an issue, but you can achieve the same thing by CMD+U
@dmortim3 I wish running individual test cases from test navigator was possible, but it is not at this moment. It has to do with how Xcode handles runtime XCTestCase.
But you can tag your features and scenarios and run them by tag!

**Comment by dmortim3** [comment]
Yes this is exactly what I am doing. WAs also looking at looking at opt-out tagging such as @manual. I don't think cucumberish supports this atm, but it could be added. Will be deciding this week if I will be going down this route.

I'm finding Cucumberish really useful. Thanks.
