### ISSUE TITLE
No such module 'Cucumberish' 

### ISSUE THREAD

**Issue by bartzet** [Ahmed-Ali/Cucumberish#84]
I am getting this error `No such module 'Cucumberish'`

![image](https://user-images.githubusercontent.com/23279455/30977319-231da5a4-a46f-11e7-981b-6239f6c6885c.png)

Cucumberish is successfully installed via Pods and Project builds fine as well. Cleaned the project , deleted derived data and still no luck.

Anyone experienced that issue?

**Comment by dgommers** [comment]
Have not experienced it before. Are you sure the Cucumberish dependency is added to the same target as the code? It doesn't look like it.

Maybe you can share your Podfile or even project file?

**Comment by junweimah** [comment]
hi 

I am getting the same error.

> Are you sure the Cucumberish dependency is added to the same target as the code?

Sorry but how can I do this? I follow everything on the swift setup guide and got this error in `CucumberishInitializer.swift` class when running test. Build project is fine though

**Comment by bartzet** [comment]
I have created a working example project here and blog post
https://github.com/novoda/ios-demos/tree/master/Cucumberish-demo
https://blog.novoda.com/cucumberish-bdd-testing-framework-for-ios-applications-sample-application/

hope you find it useful

**Comment by junweimah** [comment]
Thanks for the quick reply, will check it out

**Comment by junweimah** [comment]
I added this in my pod file

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```

then my project cant build with the error `Alamofire' does not contain bitcode.` How can I only disable bitcode the cucumberish only?

**Comment by junweimah** [comment]
I found it here: 

![image](https://user-images.githubusercontent.com/21700014/59243872-c1e22980-8c44-11e9-9766-7a5413aa0d05.png)

And removed the block of code in podfile. Now I can import Cucumberish
