### ISSUE TITLE
Accessing the JSON reports

### ISSUE THREAD

**Issue by Vinoth7** [Ahmed-Ali/Cucumberish#86]
Hi all,
I have managed to integrate cucumberish into my project successfully and can't wait to use. Now I am looking to extract the generated **JSON** reports out from iOS Simulator to report as HTML in Jenkins. As it stored in `NSDocumentDirectory` its bit hard to get out. I am not sure if there is an easy way of extracting the generated report.

Sorry for creating this as an issue. I couldn't find any easy way of clarifying.

**Comment by Vinoth7** [comment]
Sorry it’s my bad. Can able to use project base path to store the generated JSON report.

**Comment by olyv** [comment]
sorry, I am still not sure whre json reports are located after test run, can anyone advise?
