### ISSUE TITLE
how does regex work in Cucumberish?

### ISSUE THREAD

**Issue by abbood** [Ahmed-Ali/Cucumberish#9]
@Ahmed-Ali 
I was trying to understand this syntax you have

```
 MatchAll(@"^I should see \"([^\\\"]*)\" in (?:the )?\"([^\\\"]*)\" (?:button|view|label)$" ,  ^void(NSArray *args, id userInfo) {
     //Step implementation goes here
     //The definition string in this case can match all the following steps
     //When I should see "Button Title" in "MyButton" button
     //Then I should see "Button Title" in "MyButton" button
     //And I should see "Button Title" in "MyButton" button
     //But I should see "Button Title" in "MyButton" button
 });
```

b/c some of my own expressions weren't recognized properly.. 
So i created [this playground](https://gist.github.com/abbood/dfdbd235501bb96037f29426a420c54b).. and your patterns aren't recognized by the regular swift regex matchers.. can you please elaborate a bit? are you using a different regex engine under the hood or something?

**Comment by Ahmed-Ali** [comment]
Cucumberish uses the builtin regex API.
For the steps; first Gherkin parser parses the whole feature file and pass the step with data structure something like that
`
{
"keyword" : "When",
"text" : "I tap on the button"
}
`

Based on the keyword, I limit my matching with only the registered "When" steps.
Then I loop on these steps and try to evaluate their regular expression against the passed step text.
And use the first matching steps. So there is nothing fancy behind the scenes.

Check the file method
`- (CCIStepDefinition *)findDefinitionForStep:(CCIStep *)step amongDefinitions:(NSArray *)definitions;`

In the file https://github.com/Ahmed-Ali/Cucumberish/blob/master/Cucumberish/Core/Managers/CCIStepsManager.m

Line 90

**Comment by abbood** [comment]
excellent thanks for the info
